
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;


/**
 *
 * @author Andrew Hyun
 */
public class alarmSoundDialog extends javax.swing.JDialog {

    public static Clip clip;
    static File f = new File("Alarm.wav");
    private static boolean alarmOn = true;
    private String date;
    private String time;
    private String reason;
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    
    public alarmSoundDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    //constructor
    public alarmSoundDialog(String a, String b, String c) throws 
            UnsupportedAudioFileException, LineUnavailableException, 
            IOException, InterruptedException{
        initComponents();   
        //initialize variables
        date = a;
        time = b;
        reason = c;
        //create message
        alarmMessage.setText("Alarm for " + date + ".");
        alarmMessage2.setText("At: " + time);
        alarmMessage3.setText("Reason: " + reason);
        //show alarmSoundDialog
        this.setVisible(true);
    
    }
    
    public static void music() throws UnsupportedAudioFileException,
            LineUnavailableException, IOException, InterruptedException{
        AudioInputStream in = AudioSystem.getAudioInputStream(f);
        clip = AudioSystem.getClip();
        clip.open(in);
        clip.loop(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stopAlarm = new javax.swing.JButton();
        alarmMessage = new javax.swing.JLabel();
        alarmMessage2 = new javax.swing.JLabel();
        alarmMessage3 = new javax.swing.JLabel();
        BG_alarmSoundDialog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("alarmSoundDialog");
        setAlwaysOnTop(true);
        setLocation(dim.width/2 -200, dim.height/2 - 150);
        setModal(true);
        setName("alarmSoundDialog"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        setType(java.awt.Window.Type.POPUP);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stopAlarm.setFont(new java.awt.Font("DS-Digital", 0, 15)); // NOI18N
        stopAlarm.setForeground(new java.awt.Color(255, 0, 102));
        stopAlarm.setText("Stop Alarm");
        stopAlarm.setMaximumSize(new java.awt.Dimension(110, 25));
        stopAlarm.setPreferredSize(new java.awt.Dimension(100, 25));
        stopAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopAlarmActionPerformed(evt);
            }
        });
        getContentPane().add(stopAlarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 210, 150, -1));

        alarmMessage.setFont(new java.awt.Font("DS-Digital", 0, 25)); // NOI18N
        alarmMessage.setForeground(new java.awt.Color(51, 204, 255));
        alarmMessage.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(alarmMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 370, 50));

        alarmMessage2.setFont(new java.awt.Font("DS-Digital", 0, 25)); // NOI18N
        alarmMessage2.setForeground(new java.awt.Color(51, 204, 255));
        alarmMessage2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(alarmMessage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 70, 370, 50));

        alarmMessage3.setFont(new java.awt.Font("DS-Digital", 0, 25)); // NOI18N
        alarmMessage3.setForeground(new java.awt.Color(51, 204, 255));
        alarmMessage3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(alarmMessage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 370, 50));

        BG_alarmSoundDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG alarmSoundDialog.PNG"))); // NOI18N
        BG_alarmSoundDialog.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(BG_alarmSoundDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopAlarmActionPerformed
        alarmOn = false;
        clip.stop();
        this.dispose();
    
    }//GEN-LAST:event_stopAlarmActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            music();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(alarmSoundDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(alarmSoundDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(alarmSoundDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(alarmSoundDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alarmSoundDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alarmSoundDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alarmSoundDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alarmSoundDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                alarmSoundDialog dialog = new alarmSoundDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_alarmSoundDialog;
    private javax.swing.JLabel alarmMessage;
    private javax.swing.JLabel alarmMessage2;
    private javax.swing.JLabel alarmMessage3;
    private javax.swing.JButton stopAlarm;
    // End of variables declaration//GEN-END:variables
}
